In [15]:
class PeopleMyClass:
    def __init__(self,firstname,lastname,age):
        self.firstname = name
        self.lastname = lastname
        self.age = age
    def show(self):
        return f'name = {self.firstname},lastname = {self.lastname},  age= {self.age}' 
name = input('enter name ')
lastname = input('enter last name ')
age = int(input('enter age '))
x = PeopleMyClass(name, lastname, age)
print(x.show)

enter name Tina
enter last name Babakhanyan
enter age 35
<bound method PeopleMyClass.show of <__main__.PeopleMyClass object at 0x7ff03000c610>>


In [68]:
import numpy as np
arr1 = np.arange(64).reshape(4,4,4)
print('original array:')
print(arr1)
arr2 = arr1.sum(axis=1)
arr3 =arr1.sum(axis=2)
arr4 = np.add(arr2,arr3)
print('second array:')
print(arr2)
print('third array')
print(arr3)
print('sum array')
print(arr4)

original array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
second array:
[[ 24  28  32  36]
 [ 88  92  96 100]
 [152 156 160 164]
 [216 220 224 228]]
third array
[[  6  22  38  54]
 [ 70  86 102 118]
 [134 150 166 182]
 [198 214 230 246]]
sum array
[[ 30  50  70  90]
 [158 178 198 218]
 [286 306 326 346]
 [414 434 454 474]]
