In [2]:
import numpy as np
from numpy import random
from numpy import loadtxt

In [316]:
np.random.seed(100)
a=np.random.uniform(1,50,20) 
x= np.sort(a)
print(x[-5:])

[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [3]:
np.random.seed(100)
#a=np.random.uniform(1,50,20)
a = [12,4,5,6,7,12,5,3,8,10,20,10]
b,indices = np.unique(a,return_counts =True)
values,count =np.unique(a,return_counts=True)
#print(values,count)
print([a,indices])

[[12, 4, 5, 6, 7, 12, 5, 3, 8, 10, 20, 10], array([1, 1, 2, 1, 1, 1, 2, 2, 1])]


In [318]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
arr = np.array([arr1,arr2,arr3])
print(arr)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


/var/folders/xf/qvg6j60s7hddvx8mt5qky8gr0000gn/T/ipykernel_42789/502016437.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([arr1,arr2,arr3])


In [319]:
a = np.random.randint(200,size =[4,5])
a1 = np.random.randint(200,size =[4,5])
print(a)
print(a1)

[[  8  24  67 103  87]
 [ 79 176 138  94 180]
 [ 98  53  66  14  34]
 [ 24 143 107  60  58]]
[[144 137  93  86 130]
 [155 108 132 159 129]
 [141 100   4  91 187]
 [ 67 135  49 175 193]]


In [320]:
from math import sqrt
def pol(x,y):
    r = np.sqrt(x**2 +y**2)
    phi = np.arctan2(y,x)
    return(r,phi)
x = np.random.randint(100,size=(10,2))
y = np.random.randint(100,size=(10,2))
print(pol(x,y))

(array([[ 88.41379983,  57.72347876],
       [ 64.66065264,  88.60022573],
       [108.97706181,  17.11724277],
       [118.40608092,  23.02172887],
       [102.4890238 ,  65.2533524 ],
       [ 74.95331881,  73.1641989 ],
       [ 75.07329752,  95.81753493],
       [102.88342918,  95.38343672],
       [ 65.80273551,  86.76404785],
       [ 44.        ,  22.20360331]]), array([[0.80939356, 1.32581766],
       [0.55368132, 0.64124378],
       [0.74645682, 1.45368758],
       [0.6536359 , 0.60005021],
       [0.29706421, 0.26356388],
       [0.78539816, 1.19282802],
       [0.72885473, 1.25234609],
       [1.08541301, 1.05555136],
       [0.93641351, 1.11745763],
       [0.        , 0.62548504]]))


In [321]:
np.random.seed(50)
a = np.random.uniform(1,10,10)
max_value = np.max(a)
new_arr = np.where(a == max_value,a == 0,a)
print(a)
print(new_arr)


[5.45141481 3.05274794 3.29926531 4.56696919 4.39583588 9.96916807
 4.6737748  7.94704595 7.84483019 3.79008414]
[5.45141481 3.05274794 3.29926531 4.56696919 4.39583588 0.
 4.6737748  7.94704595 7.84483019 3.79008414]


In [322]:
np.random.seed(50)
arr =np.random.uniform(1,10,5)
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) 5.451414809842193
(1,) 3.052747940044026
(2,) 3.299265313814902
(3,) 4.566969187504992
(4,) 4.395835879220116


In [323]:
np.random.seed(500)
arr = np.random.uniform(10,20,40)
print(arr)
index = (np.abs(arr)).argmin()
print(arr[index])

[16.93679527 10.61716993 16.66611597 15.59208937 10.85110623 13.92419057
 14.97077527 13.32149075 13.42338452 13.65636831 18.50625783 14.48497444
 13.16472037 13.61733169 14.50722428 19.15268064 14.59958581 12.73679458
 19.17496117 14.59532223 15.4459121  16.90690372 18.30838076 16.35909311
 16.49817168 19.53758332 15.69954373 16.35201496 10.36462238 17.49126757
 18.58068435 14.85407339 12.32161767 15.03388043 11.36131889 11.73070303
 11.04958344 12.43990549 16.60723502 16.0138769 ]
10.364622378380297


In [242]:
import numpy as np
arr =np.array([3,5,7,8,10,20,30],dtype='f')
arr1 = arr.astype('i')
print(arr1.dtype)


int32


In [282]:
import numpy as np
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
a = s.reshape(500,2)
print(a)

[[-1.78871351e-01 -3.76039913e-02]
 [-1.70719652e-01  9.99355682e-02]
 [ 2.05808034e-01 -5.12436530e-02]
 [-2.46086093e-02 -1.29127312e-01]
 [-4.01140400e-02 -1.88836551e-01]
 [-4.70295147e-02 -8.31025739e-02]
 [-6.21611157e-02 -4.25489322e-04]
 [-1.57377895e-01  1.12319816e-01]
 [-2.82491342e-02  2.89599694e-02]
 [ 9.67020815e-02 -1.57175806e-01]
 [ 1.21926809e-01  1.66489543e-02]
 [-3.29784564e-02 -1.18243625e-02]
 [ 1.47244961e-01 -1.28505600e-01]
 [-3.82745541e-03  1.14146379e-01]
 [ 5.39897155e-02 -3.06380962e-02]
 [ 4.63909893e-02  4.82004017e-02]
 [-9.77977906e-02 -1.21572494e-01]
 [-6.10415562e-02 -1.33056900e-01]
 [ 1.97197502e-01  5.13516143e-02]
 [ 1.19799169e-03  1.26689990e-01]
 [-2.13286464e-02 -6.30147927e-02]
 [-1.03060029e-01  6.11152521e-02]
 [-1.45540169e-01  1.91493223e-02]
 [ 9.95539763e-03  1.05925188e-01]
 [ 6.20340720e-02 -1.05193238e-02]
 [ 1.51555513e-02 -1.29206952e-02]
 [ 5.11772662e-02 -1.60431993e-01]
 [-2.65212749e-02  1.00326025e-01]
 [-3.03405884e-02  3

In [370]:
x = np.random.randint(200,size=(5,4))
print(x)
print(x.mean(axis=1))

[[ 64  45 187 137]
 [141  67 126  79]
 [ 82  84  79 141]
 [ 75  49  88  81]
 [ 39 124  38 165]]
[108.25 103.25  96.5   73.25  91.5 ]


In [63]:
x = np.arange(256).reshape(16,16)
print('original array:')
print(x)
k = np.sum(x[14:],axis=0)
print('sum k:')
print(k)
y = k.reshape(4,4)
print('reshaped array:')
print(y)

original array:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 

In [86]:
a = np.ones((16,16))
b = 4
c = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0),
                                       np.arange(0, a.shape[1], b), axis=1)
print ('input array')
print (a)
print ('block sum')
print (c)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [504]:
a = np.arange(20).reshape(5,4)
print('original array:')
print(a)
a[[0, 2], :] = a[[2, 0], :]
print('swapt array:')
print(a)

original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
swapt array:
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]]


In [24]:
a = np.array([3,6,8,9,10,12,23])
b = np.array([23,56,34,12,89,100,0])
c = np.einsum('i,i',a,b)
print(c)

2875


In [26]:
a = np.array([3,6,8,9,10,12,23])
b = np.array([23,56,34,12,89,100,0])
c =np.inner(a,b)
print(c)

2875


In [9]:
a = np.array([3,6,8,9,10,12,23])
b = np.array([23,56,34,12,89,100,0])
c = np.outer(a,b)
print(c)

[[  69  168  102   36  267  300    0]
 [ 138  336  204   72  534  600    0]
 [ 184  448  272   96  712  800    0]
 [ 207  504  306  108  801  900    0]
 [ 230  560  340  120  890 1000    0]
 [ 276  672  408  144 1068 1200    0]
 [ 529 1288  782  276 2047 2300    0]]


In [19]:
a = np.array([3,6,8,9,10,12,23])
b = np.array([23,56,34,12,89,100,0])
c = np.multiply(a,b)
print(c)

[  69  336  272  108  890 1200    0]


In [39]:
a = np.random.randint(100,size=(6,4))
b = np.random.randint(100,size=(6,4))
print("first array:")
print(a)
print("second array")
print(b)
array_isequal = np.isclose(a, b)
print('array isequal:')
print(array_isequal)
array_equal = np.allclose(a, b)
print('array equal:')
print(array_equal)

first array:
[[29 51 29 23]
 [26 26 66  4]
 [55 85 90 11]
 [68 35 23 53]
 [19 60 64 26]
 [53 57 93 58]]
second array
[[41 58 93 74]
 [ 1 73 47 33]
 [10  3 23 53]
 [93 99 75 75]
 [82 98 89 38]
 [41 62 39 52]]
array isequal:
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
array equal:
False


In [10]:
A = np.ones(15, [ ('position', [ ('x', int, 1),
                                   ('y', int, 1)]),
                    ('color',    [ ('r', int, 1),
                                   ('g', int, 1),
                                   ('b', int, 1)])])
print(A)

[((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))]


In [85]:
np.random.seed(100)
a = np.random.uniform(1,10,30) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b) 


[5.89064448 3.50532447 4.82065832 8.60298519 1.04246971 2.09412209
 7.03674176 8.4326748  2.23035931 6.17583996 9.02189759 2.8828191
 2.66795398 1.97539201 2.97727743 9.80761406 8.30514834 2.54746911
 8.34602274 3.46666372 4.88533765 9.46026838 8.35884441 4.02500755
 2.57869408 4.35548842 1.05119657 3.27183718 8.16096258 1.13729474]


In [47]:
n = 12
p = 20
a = np.ones(n*n)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
