In [3]:
import numpy as np
arr1 = np.array([123,456,897,98]) 
arr2 = np.array([34,67,456,590])
res = arr1 + arr2
res

array([ 157,  523, 1353,  688])

In [4]:
import numpy as np
x = np.array([[2,4,6],[5,6,7]])
y = np.array(3)
res = x * y
res

array([[ 6, 12, 18],
       [15, 18, 21]])

In [18]:
import numpy as np
x = np.array([5,6,8,9,10,12])
new_arr = x.reshape(2,3)
new_arr

array([[ 5,  6,  8],
       [ 9, 10, 12]])

In [1]:
import numpy as np
x = np.array([2.5,3.5,4.5,5.5])
new_arr = x.astype('i')
print(new_arr)

[2 3 4 5]


In [1]:
import numpy as np
x = np.array([1101,1010,1111,1100])
y = x.astype('b')
print(y)

[ 77 -14  87  76]


In [6]:
import numpy as np
arr1 = ([3,5,6])
arr2 = ([5,6,9])
for i in arr1:
    for j in arr2:
        if i == j:
            print(i)
          

5
6


In [3]:
import numpy as np
x = np.array([3,4,5,6])
y = np.array([3,4,7,9])
new_arr = np.dstack([x,y])

In [33]:
new_arr

array([[3, 3],
       [4, 4],
       [5, 7],
       [6, 9]])