In [91]:
import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
arr =np.full((3, 3), True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [84]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 = arr[arr % 2 == 1]
print(arr1)

[1 3 5 7 9]


In [88]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)
   

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [75]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
for i in a:
    if i not in b:
        c = np.delete(a,i,0)
print(c)
        
       

[1 2 3 4]


In [102]:
def max(i, j):
   
    if i >= j:
        return i
    else:
        return j
    
pair_max = np.vectorize(max, otypes=[float])
    
a = np.array([4, 10, 8, 7, 5, 4, 6])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([ 6., 10.,  8.,  8.,  9.,  7.,  6.])

In [110]:
arr = np.arange(9).reshape(3,3)
arr1 = arr[:, [1,0,2]]
print(arr1)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [159]:
from numpy import random
x = np.random.randint(low=5,high=10,size=(5,3))
y = x.astype('f')
print(y)

[[9. 9. 8.]
 [5. 7. 5.]
 [7. 6. 5.]
 [9. 7. 5.]
 [9. 6. 7.]]


In [181]:
x = np.random.random((5,3))
y = x.astype('f')
print(y)

[[0.5905395  0.21031515 0.19477044]
 [0.51237184 0.77666646 0.8326248 ]
 [0.10073986 0.24545254 0.7324131 ]
 [0.98785216 0.3820154  0.04056815]
 [0.37918568 0.66757274 0.9021576 ]]


In [5]:
import numpy as np
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
